In [2]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 


In [5]:
print(a.shape)

(2, 3)


In [7]:
b = a.reshape(3,2) 
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
a = np.arange(24) 
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
a = np.arange(24) 
a.ndim  

# now reshape it 
b = a.reshape(2,4,3) 
print (b) 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [10]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


In [11]:
x = np.empty([3,2], dtype = int) 
print (x)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
x = np.zeros(5) 
print (x)

[0. 0. 0. 0. 0.]


In [13]:
x = np.zeros((5,), dtype = np.int) 
print (x)

[0 0 0 0 0]


In [14]:
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print (x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [15]:
x = [1,2,3] 
a = np.asarray(x) 
print (a)

[1 2 3]


In [16]:
x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[1. 2. 3.]


In [18]:
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)

[(1, 2, 3) (4, 5)]


In [23]:
x = np.linspace(10,20,5) 
print (x)

[10.  12.5 15.  17.5 20. ]


In [24]:
x = np.linspace(10,20, 5, endpoint = False) 
print (x)

[10. 12. 14. 16. 18.]


In [25]:
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [26]:
a = np.logspace(1,10,num = 10, base = 2) 
print (a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [28]:
a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [29]:
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [31]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]')
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [34]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...]) 
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [35]:
import numpy.matlib 


a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [37]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print (np.vdot(a,b))

130


In [38]:
print (np.inner(np.array([1,2,3]),np.array([0,1,0])))

2


In [39]:
a = np.array([[1,2], [3,4]]) 

print ('Array a:') 
print (a) 
b = np.array([[11, 12], [13, 14]]) 

print ('Array b:') 
print (b) 

print ('Inner product:') 
print (np.inner(a,b))

Array a:
[[1 2]
 [3 4]]
Array b:
[[11 12]
 [13 14]]
Inner product:
[[35 41]
 [81 95]]


In [50]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [51]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [53]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [54]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [56]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [58]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [59]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [60]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [61]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [62]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [63]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [64]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
