In [2]:
import numpy as np

# Task no 1
def function1():
    # create 2d array from 1,12 range 
    # dimension should be 6row 2 columns  
    # and assign this array values in x values in x variable
    # Hint: you can use arange and reshape numpy methods  
   
    x = np.arange(12).reshape(6,2)
   
    return x
myfunction=function1()
print(myfunction)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [4]:
# Task2
def function2():
    #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape 
    
    x = np.arange(10,37,dtype='float64').reshape(3,3,3)    
    return x
myfunction=function2()
print(myfunction)

[[[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]

 [[28. 29. 30.]
  [31. 32. 33.]
  [34. 35. 36.]]]


In [5]:
#task3
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
    
    b=a[a%7==0]
    x=b[b%5==0]
    return x
myfunction=function3()
print(myfunction)

[ 35  70 105 140 175 210 245 280 315 350 385 420 455 490 525 560 595 630
 665 700 735 770 805 840 875 910 945 980]


In [6]:
#task4
def function4():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
    arr[:,[0, 1]] = arr[:,[1, 0]]
    return arr
myfunction=function4()
print(myfunction)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [7]:
#task5
def function5():
    #Create a null vector of size 20 with 4 rows and 5 columns with numpy function
   
    z = np.zeros(20).reshape(4,5)
  
    return z
myfunction=function5()
print(myfunction)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#task6
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
   
    arr = np.zeros(10)
    arr[4] = 10
    arr[7] = 20
  
    return arr
myfunction=function6()
print(myfunction)

[ 0.  0.  0.  0. 10.  0.  0. 20.  0.  0.]


In [12]:
#task7
def function7():
    #  Create an array of zeros with the same shape and type as X. Dont use reshape method
    x = np.arange(4, dtype=np.int64)
  
    return np.zeros(4,dtype=np.int64) #write your code here
myfunction=function7()
print(myfunction)

[0 0 0 0]


In [13]:
#task8
def function8():
    # Create a new array of 2x5 uints, filled with 6.
    
    x = np.full((2, 5), 6)#write your code here
  
    return x
myfunction=function8()
print(myfunction)

[[6 6 6 6 6]
 [6 6 6 6 6]]


In [14]:
#task9
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    
    a = np.arange(2,102,2) # write your code here
  
    return a
myfunction=function9()
print(myfunction)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [15]:
#task10
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    arr[0] = arr[0] - 1
    arr[1] = arr[1] - 2
    arr[2] = arr[2] - 3
    subt = arr # write your code here 
  
    return subt


[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [16]:
#task11
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.
    
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    ans = np.where(arr%2 == 1, -1, arr)#write your code here 
  
    return ans
myfunction=function11()
print(myfunction)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [17]:
#task12
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = np.stack([arr[0],arr[0],arr[0],arr[1],arr[1],arr[1],arr[2],arr[2],arr[2],arr[0],arr[1],arr[2],arr[0],arr[1],arr[2],arr[0],arr[1],arr[2]]) #write your code here 
  
    return ans
myfunction=function12()
print(myfunction)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [18]:
#task13
def function13():
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    ans = arr#write your code here 
  
    return ans
myfunction=function13()
print(myfunction)

[ 2  6  1  9 10  3 27]


In [20]:
import numpy as np

#Task17
def function17():
    # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
    arr = np.arange(1,10*10+1).reshape((10,10))
    return np.where((arr%3==0) & (arr%5==0), 'Yes', 'No')
myfunction=function17()
print(myfunction)

[['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No']
 ['No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No']
 ['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes']
 ['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No']
 ['No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No']
 ['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes']
 ['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No']
 ['No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No']
 ['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes']
 ['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No']]
